<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>livox_ros_driver2</name>
  <version>1.0.0</version>
  <description>Device driver for Livox 3D lidars.</description>
  <maintainer email="dev@livoxtech.com">Livox Dev Team</maintainer>
  <author email="dev@livoxtech.com">Livox Dev Team</author>
  <license>MIT</license>

  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>

  <group condition="${ROS_VERSION} == 1">
    <depend>roscpp</depend>
    <depend>rospy</depend>
    <depend>rosbag</depend>
    <depend>pcl_ros</depend>

    <buildtool_depend>catkin</buildtool_depend>

    <build_depend>message_generation</build_depend>

    <exec_depend>message_runtime</exec_depend>
  </group>

  <group condition="${ROS_VERSION} == 2">
    <depend>rclcpp</depend>
    <depend>rclcpp_components</depend>
    <depend>rcutils</depend>
    <depend>pcl_conversions</depend>
    <depend>rcl_interfaces</depend>
    <depend>libpcl-all-dev</depend>

    <buildtool_depend>ament_cmake_auto</buildtool_depend>
    
    <build_depend>rosidl_default_generators</build_depend>
    
    <exec_depend>rosbag2</exec_depend>
    <exec_depend>rosidl_default_runtime</exec_depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <member_of_group>rosidl_interface_packages</member_of_group>
  </group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

    